use std::collections::HashMap;

use clap::Command;

use crate::banner;
use crate::color;

/// Groups shown in `--help`, in display order. Command names here must match the
/// `Command` enum variants' kebab-case names in `cli/mod.rs`; anything not listed
/// (there shouldn't be any) simply wouldn't show up, so keep this in sync when adding
/// a subcommand.
const CATEGORIES: &[(&str, &[&str])] = &[
    ("Tasks", &["new", "show", "ls", "edit", "status", "comment", "label", "log", "export", "epic", "link"]),
    ("Sync", &["clone", "push", "pull"]),
    ("Repos & Projects", &["register", "unregister", "repos", "projects"]),
    ("Config", &["key", "fields", "automation"]),
    ("Other", &["completions", "man", "skills", "help"]),
];

/// Builds the full `--help` / `-h` text: banner on top, then commands grouped into
/// `CATEGORIES` instead of clap's single flat list. clap 4.6 has no built-in concept
/// of multiple subcommand headings (`next_help_heading` only groups args), so this
/// replaces the auto-generated body wholesale via `Command::override_help` — see
/// `lib.rs::run`. Per-subcommand help (`<bin> new --help`) is untouched and still
/// auto-generated by clap.
pub(crate) fn render(command: &Command, bin_name: &str) -> String {
    let subs: HashMap<&str, &Command> = command.get_subcommands().map(|c| (c.get_name(), c)).collect();
    let name_width = subs.keys().map(|n| n.len()).max().unwrap_or(0);

    let mut out = String::new();
    out.push_str(&banner::help_banner());
    out.push('\n');

    if let Some(about) = command.get_about() {
        out.push_str(&about.to_string());
        out.push_str("\n\n");
    }

    out.push_str(&format!("{} {bin_name} [COMMAND]\n\n", color::heading("Usage:")));

    for (title, names) in CATEGORIES {
        let entries: Vec<(&str, String)> = names
            .iter()
            .filter_map(|name| {
                subs.get(name).map(|c| (*name, c.get_about().map(ToString::to_string).unwrap_or_default()))
            })
            .collect();
        if entries.is_empty() {
            continue;
        }
        out.push_str(&format!("{}\n", color::heading(&format!("{title}:"))));
        for (name, about) in entries {
            let padded = format!("{name:<name_width$}");
            out.push_str(&format!("  {}  {about}\n", color::cyan(&padded)));
        }
        out.push('\n');
    }

    out.push_str(&format!("{}\n", color::heading("Options:")));
    out.push_str("  -h, --help     Print help\n");
    out.push_str("  -V, --version  Print version\n\n");

    out.push_str(&format!("Run '{bin_name} <command> --help' for details on a specific command.\n"));

    out
}
